services:
  github-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: github-mcp-server:latest
    container_name: github-mcp-server
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - mcp-network

  nginx:
    image: nginx:alpine
    container_name: github-mcp-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - github-mcp-server
    restart: unless-stopped
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge